      description: Collection of <<resourcePathName|!singularize>>.
      get:
        description: Retrieve a list of <<resourcePathName|!singularize>> from repository.
        responses:
          200:
            description: "Returns a list of <<resourcePathName|!singularize>> items"
            body:
              text/xml:
                #schema: oai-pmh
                example:
                  strict: false
                  value: <<exampleCollection>>
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "Internal server error, contact administrator"
